### ISSUE TITLE
Achei Problemas!

### ISSUE THREAD

**Issue by GuilhermeRossato** [sergiocabral/femass#1]
Primeiro que quem usa javascript já começou errado o projeto

Segundo que quem usa typescript tá duplamente errado

Essa geração está perdida, tudo está muito fácil, no meu tempo não era assim! Este projeto está , este projeto não tem como dar certo! Ainda dá tempo de usar C++, Java, Ruby on Rails, ou Python!

Eu nem sei que projeto vc tá fazendo só passei pra encher o saco kkkk

Esse tal de Next.js é um framework maneiro né? Definição de rotas simples, organização livre, hotreloading rápido e que funciona em desenvolvimento, depois o build tem cache de página e de imagens automaticamente, é fácil de fazer API e facil de fazer paginas dinâmicas, e o melhor de tudo são os Server Actions: o frontend chamando uma função do backend que chega tipadinha,  que satisfação!

Desculpa NextJs é como ter uma AirFry vc tem que avisar pras pessoas como é bom kkkkk

Um salve e boa sorte no projeto!

**Comment by sergiocabral** [comment]
ushauhsauhsahus você você vendo, @GuilhermeRossato ... projeto apagado
e aí... como você está? ainda investindo nas lives?

**Comment by GuilhermeRossato** [comment]
Nem um pouco, peguei um contrato bom na gringa e depois que saí fiquei 4 meses de férias só curtindo e focado na vida fora de casa. Agr voltei a essa vida de projetos e trampo mas nada de live por enquanto

**Comment by sergiocabral** [comment]
é um bug isso aqui? eu apaguei o repo, mas se você comentar de volta o repo reaparece... antes de comentar veja se consegue acessar o link: https://github.com/sergiocabral/femass
